# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    artifactName: drop
    itemPattern: '*.exe'

steps:
- task: ArchiveFiles@2
  displayName: 'Archive $(Agent.ReleaseDirectory)\SashaRepin2.Cl2019\drop\UI\bin\Release\'
  inputs:
    rootFolderOrFile: '$(Agent.ReleaseDirectory)\SashaRepin2.Cl2019\drop\UI\bin\Release\'
    archiveFile: '$(Agent.ReleaseDirectory)\SashaRepin2.Cl2019\drop\$(Build.BuildId).zip'
    verbose: true

steps:
- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: SashaRepin2
    repositoryName: SashaRepin2/UI
    tagSource: manual
    tag: '$(Release.ReleaseName)'
    title: '$(Release.ReleaseName)'
    releaseNotesSource: input
    releaseNotes: '$(Release.ReleaseName)'
    assets: |
     $(Agent.ReleaseDirectory)\SashaRepin2.UI\drop\*.zip
     

